# Generated by Django 2.1.7 on 2021-11-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211031_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_images',
            field=models.ImageField(blank=True, default='icon.png', null=True, upload_to=''),
        ),
    ]
